#first load all necessary modules and create lemmatization function
##FIRST NEED TO INSTALL QUANTEDA##
library(quanteda)

setwd("/Users/jo/Dropbox/SMaPP/Mass Level Tweets")

#load the tweets
cons_data <- read.csv('cons_tweets.csv', header=TRUE, stringsAsFactors=FALSE)
cons_twts <- corpus(cons_data, text_field = "text")
cons_twts <- char_tolower(cons_twts)
wc_cons <- ntoken(cons_twts)
sum(wc_cons)
rm(cons_data)
gc()


lib_data <- read.csv('lib_tweets.csv', header=TRUE, stringsAsFactors=FALSE)
lib_twts <- corpus(lib_data, text_field = "text")
lib_twts <- char_tolower(lib_twts)
wc_lib <- ntoken(lib_twts)
sum(wc_lib)
rm(lib_data)
gc()

#run the tweets through top word procedures for conservatives
#run the tweets through top word procedures
#run the tweets through top word procedures
harm_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=harm_dict, valuetype="glob")
topfeatures(harm_cons, n = 10, decreasing = TRUE, ci = 0.95)
fairness_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=fairness_dict, valuetype="glob")
topfeatures(fairness_cons, n = 10, decreasing = TRUE, ci = 0.95)
ingroup_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=ingroup_dict, valuetype="glob")
topfeatures(ingroup_cons, n = 10, decreasing = TRUE, ci = 0.95)
authority_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=authority_dict, valuetype="glob")
topfeatures(authority_cons, n = 10, decreasing = TRUE, ci = 0.95)
purity_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=purity_dict, valuetype="glob")
topfeatures(purity_cons, n = 10, decreasing = TRUE, ci = 0.95)
i_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=i_dict, valuetype="glob")
topfeatures(i_cons, n = 10, decreasing = TRUE, ci = 0.95)
we_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=we_dict, valuetype="glob")
topfeatures(we_cons, n = 10, decreasing = TRUE, ci = 0.95)
posemo_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=posemo_dict, valuetype="glob")
topfeatures(posemo_cons, n = 10, decreasing = TRUE, ci = 0.95)
negemo_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=negemo_dict, valuetype="glob")
topfeatures(negemo_cons, n = 10, decreasing = TRUE, ci = 0.95)
anx_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=anx_dict, valuetype="glob")
topfeatures(anx_cons, n = 10, decreasing = TRUE, ci = 0.95)
anger_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=anger_dict, valuetype="glob")
topfeatures(anger_cons, n = 10, decreasing = TRUE, ci = 0.95)
social_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=social_dict, valuetype="glob")
topfeatures(social_cons, n = 10, decreasing = TRUE, ci = 0.95)
tentat_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=tentat_dict, valuetype="glob")
topfeatures(tentat_cons, n = 10, decreasing = TRUE, ci = 0.95)
certain_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=certain_dict, valuetype="glob")
topfeatures(certain_cons, n = 10, decreasing = TRUE, ci = 0.95)
feel_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=feel_dict, valuetype="glob")
topfeatures(feel_cons, n = 10, decreasing = TRUE, ci = 0.95)
affiliat_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=affiliat_dict, valuetype="glob")
topfeatures(affiliat_cons, n = 10, decreasing = TRUE, ci = 0.95)
achieve_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=achieve_dict, valuetype="glob")
topfeatures(achieve_cons, n = 10, decreasing = TRUE, ci = 0.95)
power_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=power_dict, valuetype="glob")
topfeatures(power_cons, n = 10, decreasing = TRUE, ci = 0.95)
risk_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=risk_dict, valuetype="glob")
topfeatures(risk_cons, n = 10, decreasing = TRUE, ci = 0.95)
past_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=past_dict, valuetype="glob")
topfeatures(past_cons, n = 10, decreasing = TRUE, ci = 0.95)
future_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=future_dict, valuetype="glob")
topfeatures(future_cons, n = 10, decreasing = TRUE, ci = 0.95)
money_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=money_dict, valuetype="glob")
topfeatures(money_cons, n = 10, decreasing = TRUE, ci = 0.95)
relig_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=relig_dict, valuetype="glob")
topfeatures(relig_cons, n = 10, decreasing = TRUE, ci = 0.95)
death_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=death_dict, valuetype="glob")
topfeatures(death_cons, n = 10, decreasing = TRUE, ci = 0.95)
inhib_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=inhib_dict, valuetype="glob")
topfeatures(inhib_cons, n = 10, decreasing = TRUE, ci = 0.95)
threat_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=threat_dict, valuetype="glob")
topfeatures(threat_cons, n = 10, decreasing = TRUE, ci = 0.95)
uncertain_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=uncertain_dict, valuetype="glob")
topfeatures(uncertain_cons, n = 10, decreasing = TRUE, ci = 0.95)
change_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=change_dict, valuetype="glob")
topfeatures(change_cons, n = 10, decreasing = TRUE, ci = 0.95)
inequal_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=inequal_dict, valuetype="glob")
topfeatures(inequal_cons, n = 10, decreasing = TRUE, ci = 0.95)
rulesrei_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=rulesrei_dict, valuetype="glob")
topfeatures(rulesrei_cons, n = 10, decreasing = TRUE, ci = 0.95)
selfdisc_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=selfdisc_dict, valuetype="glob")
topfeatures(selfdisc_cons, n = 10, decreasing = TRUE, ci = 0.95)
nurtur_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=nurtur_dict, valuetype="glob")
topfeatures(nurtur_cons, n = 10, decreasing = TRUE, ci = 0.95)
empathy_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=empathy_dict, valuetype="glob")
topfeatures(empathy_cons, n = 10, decreasing = TRUE, ci = 0.95)
achievement_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=achievement_dict, valuetype="glob")
topfeatures(achievement_cons, n = 10, decreasing = TRUE, ci = 0.95)
hedonism_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=hedonism_dict, valuetype="glob")
topfeatures(hedonism_cons, n = 10, decreasing = TRUE, ci = 0.95)
pow_Neim_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=pow_Neim_dict, valuetype="glob")
topfeatures(pow_Neim_cons, n = 10, decreasing = TRUE, ci = 0.95)
selfdirect_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=selfdirect_dict, valuetype="glob")
topfeatures(selfdirect_cons, n = 10, decreasing = TRUE, ci = 0.95)
stim_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=stim_dict, valuetype="glob")
topfeatures(stim_cons, n = 10, decreasing = TRUE, ci = 0.95)
benev_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=benev_dict, valuetype="glob")
topfeatures(benev_cons, n = 10, decreasing = TRUE, ci = 0.95)
conform_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=conform_dict, valuetype="glob")
topfeatures(conform_cons, n = 10, decreasing = TRUE, ci = 0.95)
security_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=security_dict, valuetype="glob")
topfeatures(security_cons, n = 10, decreasing = TRUE, ci = 0.95)
tradition_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=tradition_dict, valuetype="glob")
topfeatures(tradition_cons, n = 10, decreasing = TRUE, ci = 0.95)
universal_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=universal_dict, valuetype="glob")
topfeatures(universal_cons, n = 10, decreasing = TRUE, ci = 0.95)
powHV_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=powHV_dict, valuetype="glob")
topfeatures(powHV_cons, n = 10, decreasing = TRUE, ci = 0.95)
afilHV_cons <- dfm(cons_twts, verbose = FALSE, removePunct = TRUE, dictionary=afilHV_dict, valuetype="glob")
topfeatures(afilHV_cons, n = 10, decreasing = TRUE, ci = 0.95)

#run the tweets through top word procedures for libervatives
#run the tweets through top word procedures
#run the tweets through top word procedures
harm_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=harm_dict, valuetype="glob")
topfeatures(harm_lib, n = 10, decreasing = TRUE, ci = 0.95)
fairness_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=fairness_dict, valuetype="glob")
topfeatures(fairness_lib, n = 10, decreasing = TRUE, ci = 0.95)
ingroup_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=ingroup_dict, valuetype="glob")
topfeatures(ingroup_lib, n = 10, decreasing = TRUE, ci = 0.95)
authority_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=authority_dict, valuetype="glob")
topfeatures(authority_lib, n = 10, decreasing = TRUE, ci = 0.95)
purity_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=purity_dict, valuetype="glob")
topfeatures(purity_lib, n = 10, decreasing = TRUE, ci = 0.95)
i_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=i_dict, valuetype="glob")
topfeatures(i_lib, n = 10, decreasing = TRUE, ci = 0.95)
we_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=we_dict, valuetype="glob")
topfeatures(we_lib, n = 10, decreasing = TRUE, ci = 0.95)
posemo_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=posemo_dict, valuetype="glob")
topfeatures(posemo_lib, n = 10, decreasing = TRUE, ci = 0.95)
negemo_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=negemo_dict, valuetype="glob")
topfeatures(negemo_lib, n = 10, decreasing = TRUE, ci = 0.95)
anx_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=anx_dict, valuetype="glob")
topfeatures(anx_lib, n = 10, decreasing = TRUE, ci = 0.95)
anger_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=anger_dict, valuetype="glob")
topfeatures(anger_lib, n = 10, decreasing = TRUE, ci = 0.95)
social_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=social_dict, valuetype="glob")
topfeatures(social_lib, n = 10, decreasing = TRUE, ci = 0.95)
tentat_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=tentat_dict, valuetype="glob")
topfeatures(tentat_lib, n = 10, decreasing = TRUE, ci = 0.95)
certain_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=certain_dict, valuetype="glob")
topfeatures(certain_lib, n = 10, decreasing = TRUE, ci = 0.95)
feel_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=feel_dict, valuetype="glob")
topfeatures(feel_lib, n = 10, decreasing = TRUE, ci = 0.95)
affiliat_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=affiliat_dict, valuetype="glob")
topfeatures(affiliat_lib, n = 10, decreasing = TRUE, ci = 0.95)
achieve_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=achieve_dict, valuetype="glob")
topfeatures(achieve_lib, n = 10, decreasing = TRUE, ci = 0.95)
power_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=power_dict, valuetype="glob")
topfeatures(power_lib, n = 10, decreasing = TRUE, ci = 0.95)
risk_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=risk_dict, valuetype="glob")
topfeatures(risk_lib, n = 10, decreasing = TRUE, ci = 0.95)
past_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=past_dict, valuetype="glob")
topfeatures(past_lib, n = 10, decreasing = TRUE, ci = 0.95)
future_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=future_dict, valuetype="glob")
topfeatures(future_lib, n = 10, decreasing = TRUE, ci = 0.95)
money_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=money_dict, valuetype="glob")
topfeatures(money_lib, n = 10, decreasing = TRUE, ci = 0.95)
relig_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=relig_dict, valuetype="glob")
topfeatures(relig_lib, n = 10, decreasing = TRUE, ci = 0.95)
death_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=death_dict, valuetype="glob")
topfeatures(death_lib, n = 10, decreasing = TRUE, ci = 0.95)
inhib_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=inhib_dict, valuetype="glob")
topfeatures(inhib_lib, n = 10, decreasing = TRUE, ci = 0.95)
threat_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=threat_dict, valuetype="glob")
topfeatures(threat_lib, n = 10, decreasing = TRUE, ci = 0.95)
uncertain_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=uncertain_dict, valuetype="glob")
topfeatures(uncertain_lib, n = 10, decreasing = TRUE, ci = 0.95)
change_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=change_dict, valuetype="glob")
topfeatures(change_lib, n = 10, decreasing = TRUE, ci = 0.95)
inequal_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=inequal_dict, valuetype="glob")
topfeatures(inequal_lib, n = 10, decreasing = TRUE, ci = 0.95)
rulesrei_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=rulesrei_dict, valuetype="glob")
topfeatures(rulesrei_lib, n = 10, decreasing = TRUE, ci = 0.95)
selfdisc_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=selfdisc_dict, valuetype="glob")
topfeatures(selfdisc_lib, n = 10, decreasing = TRUE, ci = 0.95)
nurtur_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=nurtur_dict, valuetype="glob")
topfeatures(nurtur_lib, n = 10, decreasing = TRUE, ci = 0.95)
empathy_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=empathy_dict, valuetype="glob")
topfeatures(empathy_lib, n = 10, decreasing = TRUE, ci = 0.95)
achievement_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=achievement_dict, valuetype="glob")
topfeatures(achievement_lib, n = 10, decreasing = TRUE, ci = 0.95)
hedonism_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=hedonism_dict, valuetype="glob")
topfeatures(hedonism_lib, n = 10, decreasing = TRUE, ci = 0.95)
pow_Neim_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=pow_Neim_dict, valuetype="glob")
topfeatures(pow_Neim_lib, n = 10, decreasing = TRUE, ci = 0.95)
selfdirect_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=selfdirect_dict, valuetype="glob")
topfeatures(selfdirect_lib, n = 10, decreasing = TRUE, ci = 0.95)
stim_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=stim_dict, valuetype="glob")
topfeatures(stim_lib, n = 10, decreasing = TRUE, ci = 0.95)
benev_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=benev_dict, valuetype="glob")
topfeatures(benev_lib, n = 10, decreasing = TRUE, ci = 0.95)
conform_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=conform_dict, valuetype="glob")
topfeatures(conform_lib, n = 10, decreasing = TRUE, ci = 0.95)
security_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=security_dict, valuetype="glob")
topfeatures(security_lib, n = 10, decreasing = TRUE, ci = 0.95)
tradition_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=tradition_dict, valuetype="glob")
topfeatures(tradition_lib, n = 10, decreasing = TRUE, ci = 0.95)
universal_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=universal_dict, valuetype="glob")
topfeatures(universal_lib, n = 10, decreasing = TRUE, ci = 0.95)
powHV_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=powHV_dict, valuetype="glob")
topfeatures(powHV_lib, n = 10, decreasing = TRUE, ci = 0.95)
afilHV_lib <- dfm(lib_twts, verbose = FALSE, removePunct = TRUE, dictionary=afilHV_dict, valuetype="glob")
topfeatures(afilHV_lib, n = 10, decreasing = TRUE, ci = 0.95)


